---
spring:
  application:
    name: spring-cloud-eureka
  profiles: p2
server:
  port: 8000
eureka:
  instance:
    hostname: peer2
    instance-id: eureka2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer3:8000/eureka/