---
spring:
  application:
    name: spring-cloud-eureka
  profiles: p3
server:
  port: 8000
eureka:
  instance:
    hostname: peer3
    instance-id: eureka3
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8000/eureka/