---
spring:
  application:
    name: spring-cloud-eureka
  profiles: p1
server:
  port: 8000
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8000/eureka/,http://peer3:8000/eureka/
#      register-with-eureka: false
#      fetch-registry: true