---
spring:
  application:
    name: spring-cloud-eureka
  profiles: p2
server:
  port: 8000
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer3:8000/eureka/
#      register-with-eureka: false
#      fetch-registry: true