---
spring:
  application:
    name: spring-cloud-eureka
  profiles: p1
server:
  port: 8000
eureka:
  instance:
    hostname: peer1
    instance-id: eureka1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2:8000/eureka/,http://peer3:8000/eureka/