server:
  port: 9102

spring:
  application:
    name: spring-cloud-consul-producer
  cloud:
    consul:
      host: myconsul1
      port: 8500
      discovery:
        service-name: consul-producer
        hostname: peer2