---
server:
  port: 9101

spring:
  application:
    name: spring-cloud-consul-producer
  profiles: p1
  cloud:
    consul:
      host: myconsul1
      port: 8500
      discovery:
        service-name: consul-producer
        hostname: peer1
