---
spring:
  application:
    name: spring-cloud-producer

server:
  port: 9001

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
#      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/