---
spring:
  application:
    name: spring-cloud-producer
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://zipkin:8900

server:
  port: 9000

eureka:
  instance:
    hostname: myproducer
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://127.0.0.1:8000/eureka/
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/
