---
spring:
  application:
    name: spring-cloud-producer

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/