eureka:
  instance:
    hostname: zipkin

  client:
    service-url:
      #defaultZone: http://127.0.0.1:8000/eureka/
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/

server:
  port: 8900

spring:
  application:
    name: zipkin-simple-server