---
server:
  port: 8888

spring:
  application:
    name: spring-cloud-zuul-eureka

eureka:
  instance:
    hostname: mygateway
  client:
    service-url:
      #      defaultZone: http://127.0.0.1:8000/eureka/
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/
