---
spring:
  application:
    name: spring-cloud-eureka
  profiles: p3
server:
  port: 8003
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
#      register-with-eureka: false
#      fetch-registry: true