server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zdq0394/springcloud-examples/
          search-paths: config-git/configs
          username:
          password: