---
server:
  port: 9200
spring:
  application:
    name: spring-cloud-consul-consumer
  cloud:
    consul:
      host: myconsul1
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: consul-consumer
        hostname: myconsul-consumer