server:
  port: 9201
spring:
  application:
    name: spring-cloud-consul-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: consul-consumer
        register: false